spring.application.name=megasena-batch-job
spring.batch.job.name=loteriasJobMaster
spring.main.web-application-type=none

spring.jpa.hibernate.ddl-auto=update
spring.batch.jdbc.initialize-schema=always
spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

file.path.output=${FILE_OUTPUT_DIR}
quantidade.sorteios.megasena=${QUANTIDADE_SORTEIOS_MEGASENA:4}
data.megasena.jogo=3
data.quina.jogo=15



api.megasena=https://servicebus2.caixa.gov.br/portaldeloterias/api/megasena
api.quina=https://servicebus2.caixa.gov.br/portaldeloterias/api/quina

api.loterias.url=https://servicebus2.caixa.gov.br/portaldeloterias/api